name: pycurator
channels:
  - conda-forge
dependencies:
  # required
  - python>=3.10
  - pandas>=1.4.1
  - requests>=2.27.1
  - setuptools>=57.4.0

  # querying OpenML
  - openml>=0.12.2

  # querying Kaggle
  - kaggle>=1.5.12

  # testing
  - pytest

  # docs
  - sphinx

  # optional
  # save as excel
  - openpyxl